title: מחקרי השקעות
description: סקירות עומק, תזות וניתוחי שוק
theme: minima

# כתובת האתר
url: "https://eladyesh.github.io"
baseurl: "/financial_site"   # ❗️שנה לשם הריפו האמיתי

# Markdown כמו GitHub README
markdown: kramdown
kramdown:
  input: GFM

# ביטול מוחלט של אזכור GitHub
github:
  is_project_page: false
  is_user_page: false

show_downloads: false
