title: מחקרי השקעות
description: סקירות עומק, תזות וניתוחי שוק
theme: jekyll-theme-midnight

markdown: kramdown
kramdown:
  input: GFM

# ביטול כל אזכור ל-GitHub
github:
  is_project_page: false
  is_user_page: false

show_downloads: false

